### ISSUE TITLE
Style Framework

### ISSUE THREAD

**Issue by mcwhittemore** [serverless/dashboard#2]
@ac360 mentioned the idea of using bootstrap or some other style framework. This has pros and cons for modularity. In general I think inline styles work best with react, but as that is divisive and the key here is to be welcoming, +1 to bootstrap.

What do other think?

**Comment by ac360** [comment]
Bootstrap isn't a requirement.  I feels a bit bloated to me.  React's inline styles as objects are cool.  Is there any lightweight style framework that plays nicely with React?

**Comment by mcwhittemore** [comment]
I mostly deal with internal style guidelines, so sadly I'm not sure. Will google if someone else doesn't present info.

**Comment by apaatsio** [comment]
Bootstrap is bloated, but so what. I mean, we don't need to optimize mobile load times or anything, do we? 

I would go with bootstrap. The biggest benefi  is that most frontend developers are already familiar with it.

**Comment by marclar** [comment]
Mentioned [over here](https://github.com/jaws-framework/JAWS/issues/240#issuecomment-148838647) -- 2 great boilerplate projects.

For UI, this is the best thing I've ever used: http://semantic-ui.com

In case people want it, it even comes with an "Amazon" theme (you can see it in action in the "Unbelievable Theming" section).

I used it for this admin site: 

[![Mix Admin Walkthrough](http://img.youtube.com/vi/0TwjnTIPTi4/0.jpg)](http://www.youtube.com/watch?v=0TwjnTIPTi4 "Mix Admin Walkthrough")

That site uses Flux (Fluxxor, but will be transitioned to Redux in the interest of being _coool_).

**Comment by aletheia** [comment]
Have you ever checked out Lightning Design System? 
https://www.lightningdesignsystem.com/
It's quite light and thought for enterprise apps such as a dashboard. I like the widgets very much.

**Comment by dtimberlake** [comment]
Two suggestions:

1. UI Components: http://www.material-ui.com/. It follows Google's material design, looks great on admin user interfaces, and best of all doesn't interact with the DOM directly (since it was built on top of React). The documentation is very good as well.

2. Grid System: http://susy.oddbird.net/ (advanced[ish]) or pulling just the grid system from something like http://getbootstrap.com/.

**Comment by TheSharpieOne** [comment]
Just throwing this in here since there was mention of the inline style approach. Checkout [Radium](https://github.com/FormidableLabs/radium) as I believe it to be the purest solution. They also have a nice [comparison table](https://github.com/FormidableLabs/radium/tree/master/docs/comparison) with the  most popular libraries for CSS in JS for React.

**Comment by DavidWells** [comment]
We are using PostCSS + css modules now.

For more information on both checkout https://vimeo.com/173122870 and https://speakerdeck.com/davidwells/bulletproof-css-in-react
