### ISSUE TITLE
React? Why?

### ISSUE THREAD

**Issue by aletheia** [serverless/dashboard#9]
Hello is there any particular reason why you choose ReactJS for Dashboard implementation?
to my understanding a simple JQuery only approach could fit better and be more extensible.
I could help on this, please let me know about that

**Comment by eahefnawy** [comment]
Great Question Aletheia! glad you brought that up! We chose React because it's becoming the standard for UI development in the open source community. Our community seems to prefer a React solution. 

Plus, we're anticipating that our dashboard will get complex in the future, so we want to get a good start to handle that, and React seems to be the way to go!
